# Generated by Django 5.2.5 on 2025-08-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_customuser_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
