# Generated by Django 5.2.5 on 2025-08-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_customuser_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_expired',
            field=models.BooleanField(default=True),
        ),
    ]
