# Generated by Django 5.2.5 on 2025-09-01 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0024_remove_target_unique_active_target_per_staff_and_type_and_more'),
        ('users', '0010_customuser_password_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff_management.branch', verbose_name='Branch'),
        ),
    ]
