# Generated by Django 5.1.1 on 2025-06-23 15:40

import Customer.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cus_id', models.CharField(editable=False, max_length=9, primary_key=True, serialize=False, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=Customer.models.Customer.upload_to_profile, verbose_name='Profile Photo')),
                ('signature_photo', models.ImageField(blank=True, null=True, upload_to=Customer.models.Customer.upload_to_signature, verbose_name='Signature Photo')),
                ('id_scan', models.ImageField(blank=True, null=True, upload_to=Customer.models.Customer.upload_to_id_scan, verbose_name='Identity Card Photo')),
                ('mem_reg_date', models.DateField()),
                ('member_number', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('salutation', models.CharField(choices=[('Mr', 'Mr'), ('Miss', 'Miss'), ('Mrs', 'Mrs')], max_length=4)),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('middle_name1', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name2', models.CharField(blank=True, max_length=50, null=True)),
                ('surname', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=8)),
                ('is_pwd', models.BooleanField(default=False)),
                ('dob', models.DateField()),
                ('home_ownership', models.CharField(choices=[('Owned', 'Owned'), ('Rented', 'Rented')], max_length=6)),
                ('id_number', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message="ID number must be exactly 14 characters, start with 'CF' or 'CM', and end with a letter.", regex='^(CF|CM)[A-Z0-9]{11}[A-Z]$')])),
                ('card_number', models.CharField(max_length=20, unique=True)),
                ('nin_village', models.CharField(blank=True, max_length=100, null=True)),
                ('nin_parish', models.CharField(blank=True, max_length=100, null=True)),
                ('nin_s_county', models.CharField(blank=True, max_length=100, null=True)),
                ('nin_county', models.CharField(blank=True, max_length=100, null=True)),
                ('nin_district', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be exactly 12 digits, starting with '256'.", regex='^256\\d{9}$')])),
                ('phone_number2', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be exactly 12 digits, starting with '256'.", regex='^256\\d{9}$')])),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('parish', models.CharField(blank=True, max_length=100, null=True)),
                ('s_county', models.CharField(blank=True, max_length=100, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('sao_zone', models.CharField(choices=[('Bamunanika', 'Bamunanika'), ('Bukimu', 'Bukimu'), ('Busiika-Main', 'Busiika-Main'), ('Collective-A', 'Collective-A'), ('Collective-B', 'Collective-B'), ('Kabulanaka-Ngalonkalu', 'Kabulanaka_Ngalonkalu'), ('Kakakala', 'Kakakala'), ('Kikyusa', 'Kikyusa'), ('Kyetume-Bubbuubi', 'Kyetume-Bubbuubi'), ('Namawojja', 'Namawojja'), ('Sekamuli', 'Sekamuli')], max_length=50)),
                ('kin_sname', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('kin_fname', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('kin_sname2', models.CharField(blank=True, max_length=50, null=True)),
                ('kin_phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be exactly 12 digits, starting with '256'.", regex='^256\\d{9}$')])),
                ('kin_address', models.CharField(blank=True, max_length=200, null=True)),
                ('kin_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('employment', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('employer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('employer_address', models.CharField(blank=True, max_length=200, null=True)),
                ('employer_phone1', models.CharField(blank=True, max_length=15, null=True)),
                ('employer_phone2', models.CharField(blank=True, max_length=15, null=True)),
                ('income_frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('income_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='staff_management.branch')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
