# Generated by Django 5.2.5 on 2025-09-04 05:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_alter_customer_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_number',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message="ID number must be exactly 14 characters, start with 'CF' or 'CM', and end with a letter.", regex='^(CF|CM)[A-Z0-9]{11}[A-Z]$')]),
        ),
    ]
