# Generated by Django 5.2.5 on 2025-09-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_alter_customer_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
