# Generated by Django 5.2.5 on 2025-09-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_alter_customer_id_number'),
        ('staff_management', '0029_remove_target_unique_active_target_per_staff_and_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['first_name'], name='Customer_cu_first_n_b88f10_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['surname'], name='Customer_cu_surname_ea0fdf_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['member_number'], name='Customer_cu_member__8353e8_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['cus_id'], name='Customer_cu_cus_id_2daf72_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='Customer_cu_phone_378d73_idx'),
        ),
    ]
