# Generated by Django 5.1.1 on 2025-06-23 15:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Savings, Shares, Membership', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Target Type',
                'verbose_name_plural': 'Target Types',
            },
        ),
        migrations.CreateModel(
            name='Term_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termId', models.CharField(help_text='e.g., Term start year 2023, Q2 2023', max_length=50, unique=True)),
                ('date_range', models.DateField(help_text='Date range for the term')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('expiry_date', models.DateField(help_text='Expiration date of the term')),
                ('chairperson', models.CharField(help_text='Name of the chairperson', max_length=50)),
                ('secretary', models.CharField(help_text='Name of the secretary', max_length=50)),
                ('vice_chairperson', models.CharField(help_text='Name of the vice chairperson', max_length=50)),
                ('treasurer', models.CharField(help_text='Name of the treasurer', max_length=50)),
            ],
            options={
                'verbose_name': 'Term Detail',
                'verbose_name_plural': 'Term Details',
            },
        ),
        migrations.CreateModel(
            name='Delegate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegates', to='Customer.customer')),
            ],
            options={
                'verbose_name': 'Delegate',
                'verbose_name_plural': 'Delegates',
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('target_value', models.DecimalField(decimal_places=2, help_text='Target value (e.g., amount in currency, number of shares, or memberships)', max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='delegates.delegate')),
                ('target_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='delegates.targettype')),
            ],
            options={
                'verbose_name': 'Target',
                'verbose_name_plural': 'Targets',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_value', models.DecimalField(decimal_places=2, help_text='Actual value achieved (e.g., amount, shares, or memberships)', max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('transaction_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal')], default='Deposit', max_length=20)),
                ('channel', models.CharField(choices=[('Counter', 'Counter'), ('Mobile', 'Mobile Money'), ('Bank', 'Bank Transfer'), ('Other', 'Other')], default='Counter', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Unique transaction reference number', max_length=100, null=True, unique=True)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, help_text='Running balance after this transaction', max_digits=15, null=True)),
                ('transaction_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='delegates.delegate')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='delegates.target')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
