# Generated by Django 5.1.1 on 2025-06-23 15:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCustody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ID', 'Identification Document'), ('TITLE', 'Title Deed'), ('PASSPORT', 'Passport'), ('OTHER', 'Other')], max_length=20)),
                ('storage_reason', models.CharField(choices=[('COLLATERAL', 'Collateral'), ('SAFEKEEPING', 'Safekeeping'), ('OTHER', 'Other')], max_length=20)),
                ('document_description', models.TextField(blank=True, null=True)),
                ('date_received', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=200, null=True)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('next_of_kin_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('available', 'Available'), ('requested', 'Requested'), ('released', 'Released'), ('branch', 'At Branch'), ('authorised', 'Authorised'), ('delivered', 'Delivered'), ('returned', 'Returned')], default='Pending', max_length=20)),
                ('date_acknowledged', models.DateTimeField(blank=True, null=True)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('date_requested', models.DateTimeField(blank=True, null=True)),
                ('date_authorised', models.DateTimeField(blank=True, null=True)),
                ('date_released', models.DateTimeField(blank=True, null=True)),
                ('date_delivered', models.DateTimeField(blank=True, null=True)),
                ('returned_to_name', models.CharField(blank=True, max_length=200, null=True)),
                ('returned_to_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_documents', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_documents', to=settings.AUTH_USER_MODEL)),
                ('authorised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorised_documents', to=settings.AUTH_USER_MODEL)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_documents', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer')),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_documents', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_documents', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_documents', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
