# Generated by Django 5.1.1 on 2025-08-05 10:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musingo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('REQUEST', 'Request'), ('ACKNOWLEDGE', 'Acknowledge'), ('APPROVE', 'Approve'), ('AUTHORISE', 'Authorise'), ('RELEASE', 'Release'), ('DELIVER', 'Deliver'), ('RETURN', 'Return'), ('REVERSE', 'Reverse')], max_length=20)),
                ('comment', models.TextField()),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='Musingo.documentcustody')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
