# Generated by Django 5.2.5 on 2025-08-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musingo', '0002_documentactionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcustody',
            name='document_type',
            field=models.CharField(choices=[('ID', 'Identification Document'), ('Land TITLE', 'Land Title'), ('Plot Agreement', 'Plot Agreement'), ('Will', 'Will'), ('Academic Document', 'Academic Document'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='documentcustody',
            name='storage_reason',
            field=models.CharField(choices=[('COLLATERAL', 'Collateral'), ('DOCUMENT CUSTODY', 'Document Custody'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
