# Generated by Django 5.2.5 on 2025-08-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musingo', '0003_alter_documentcustody_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcustody',
            name='document_type',
            field=models.CharField(choices=[('ID', 'Identification Document'), ('Land TITLE', 'Land Title'), ('Plot Agreement', 'Plot Agreement'), ('Kibanja Agreement', 'Kibanja Agreement'), ('Will', 'Will'), ('Academic Document', 'Academic Document'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
