# Generated by Django 5.2.5 on 2025-09-05 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0005_alter_customer_id_number'),
        ('Groups', '0001_initial'),
        ('Loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='loan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Loans.loan'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grouploan',
            name='loan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Loans.loan'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer'),
        ),
        migrations.AddField(
            model_name='groupsavings',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer'),
        ),
        migrations.AddField(
            model_name='loangroup',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_groups', to='Customer.customer'),
        ),
        migrations.AddField(
            model_name='groupsavings',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings', to='Groups.loangroup'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='Groups.loangroup'),
        ),
        migrations.AddField(
            model_name='grouploan',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_loans', to='Groups.loangroup'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Groups.loangroup'),
        ),
        migrations.AddField(
            model_name='memberloanallocation',
            name='group_loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='Groups.grouploan'),
        ),
        migrations.AddField(
            model_name='memberloanallocation',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('group', 'customer')},
        ),
    ]
