# Generated by Django 5.2.5 on 2025-09-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
