# Generated by Django 5.2.5 on 2025-09-09 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_alter_customer_options_and_more'),
        ('Groups', '0002_initial'),
        ('Loans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loangroup',
            name='created_on',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='loan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='Loans.loan'),
        ),
        migrations.AlterField(
            model_name='grouploan',
            name='loan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_loan', to='Loans.loan'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='Customer.customer'),
        ),
        migrations.AlterField(
            model_name='groupsavings',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_contributions', to='Customer.customer'),
        ),
        migrations.AlterField(
            model_name='memberloanallocation',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_loan_allocations', to='Customer.customer'),
        ),
    ]
