# Generated by Django 5.2.5 on 2025-09-16 11:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0003_remove_loangroup_created_on_alter_auditlog_loan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loangroup',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
