# Generated by Django 5.2.5 on 2025-09-17 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0004_loangroup_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loangroup',
            old_name='leader',
            new_name='group_leader',
        ),
    ]
