# Generated by Django 5.1.1 on 2025-06-23 15:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Branch Code')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Branch Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Location')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffTargetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, help_text='Auto-generated code in format stt_01', max_length=10, unique=True)),
                ('stname', models.CharField(help_text='e.g., Savings, Shares, Membership', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
            ],
            options={
                'verbose_name': 'Target Type',
                'verbose_name_plural': 'Target Types',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(editable=False, max_length=20)),
                ('staff_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('other_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20)),
                ('id_type', models.CharField(choices=[('National ID', 'National ID'), ('Passport', 'Passport')], max_length=50)),
                ('id_number', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('next_of_kin_name', models.CharField(max_length=100)),
                ('next_of_kin_phone', models.CharField(max_length=20)),
                ('next_of_kin_address', models.TextField()),
                ('relationship', models.CharField(choices=[('Spouse', 'Spouse'), ('Parent', 'Parent'), ('Sibling', 'Sibling'), ('Child', 'Child'), ('Other', 'Other')], max_length=50)),
                ('date_appointed', models.DateField()),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Bank', 'Bank'), ('Mobile Money', 'Mobile Money'), ('Cash', 'Cash')], max_length=50)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('ssn', models.CharField(blank=True, max_length=50, null=True)),
                ('ssf', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paye', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('signature_file', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('id_attachment', models.FileField(blank=True, null=True, upload_to='id_attachments/')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff_management.branch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff_management.department')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff_management.position')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], default='Monthly', max_length=20)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='staff_management.staff')),
                ('target_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='staff_management.stafftargettype')),
            ],
        ),
        migrations.CreateModel(
            name='TargetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal')], default='Deposit', max_length=20)),
                ('actual_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateTimeField()),
                ('transdescription', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='staff_management.target')),
            ],
        ),
        migrations.AddConstraint(
            model_name='target',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__gte', datetime.date(2025, 6, 23))), fields=('staff', 'target_type'), name='unique_active_target_per_staff_and_type'),
        ),
    ]
