# Generated by Django 5.1.1 on 2025-06-24 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='target',
            name='unique_active_target_per_staff_and_type',
        ),
        migrations.AddConstraint(
            model_name='target',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__gte', datetime.date(2025, 6, 24))), fields=('staff', 'target_type'), name='unique_active_target_per_staff_and_type'),
        ),
    ]
