# Generated by Django 5.1.1 on 2025-07-22 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0009_remove_target_unique_active_target_per_staff_and_type_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='target',
            name='unique_active_target_per_staff_and_type',
        ),
        migrations.AddConstraint(
            model_name='target',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__gte', datetime.date(2025, 7, 22))), fields=('staff', 'target_type'), name='unique_active_target_per_staff_and_type'),
        ),
    ]
