# Generated by Django 5.1.1 on 2025-07-22 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0011_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='gm_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gm_approvals', to='staff_management.staff'),
        ),
        migrations.AddField(
            model_name='leave',
            name='hr_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_reviews', to='staff_management.staff'),
        ),
        migrations.AddField(
            model_name='leave',
            name='manager_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_reviews', to='staff_management.staff'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Manager_Reviewed', 'Manager Reviewed'), ('HR_Reviewed', 'HR Reviewed'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
