# Generated by Django 5.2.5 on 2025-09-16 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0030_systemsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsetting',
            options={'verbose_name': 'System Setting', 'verbose_name_plural': 'System Settings'},
        ),
        migrations.RemoveConstraint(
            model_name='target',
            name='unique_active_target_per_staff_and_type',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='target',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__gte', datetime.date(2025, 9, 16))), fields=('staff', 'target_type'), name='unique_active_target_per_staff_and_type'),
        ),
    ]
