# Generated by Django 5.2.5 on 2025-09-16 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0031_alter_systemsetting_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={},
        ),
    ]
