# Generated by Django 5.2.5 on 2025-09-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0032_alter_leave_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={'verbose_name': 'Leave', 'verbose_name_plural': 'Leaves'},
        ),
        migrations.AlterModelOptions(
            name='systemsetting',
            options={},
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
