# Generated by Django 5.2.5 on 2025-09-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0033_alter_leave_options_alter_systemsetting_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={},
        ),
        migrations.AlterModelOptions(
            name='systemsetting',
            options={'verbose_name': 'System Setting', 'verbose_name_plural': 'System Settings'},
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
