# Generated by Django 5.2.5 on 2025-09-17 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0034_alter_leave_options_alter_systemsetting_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='target',
            name='unique_active_target_per_staff_and_type',
        ),
        migrations.AddConstraint(
            model_name='target',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__gte', datetime.date(2025, 9, 17))), fields=('staff', 'target_type'), name='unique_active_target_per_staff_and_type'),
        ),
    ]
